### ISSUE TITLE
Make Python 3 compatible.

### ISSUE THREAD

**Issue by musically-ut** [Networks-Learning/stackexchange-dump-to-postgres#3]
This would require replacing some calls to `file` and rewriting the `print` statements as their functional form.

**Comment by yemarnevets** [comment]
Hi musically-ut, I'd like to help out with this as a first time contributor on open source. Cheers, YN

**Comment by musically-ut** [comment]
@yemarnevets Sure, go ahead!

**Comment by yemarnevets** [comment]
Great, so the process is (1) fork the repo, (2) make the changes, (3) push for your review? Presumably I'd need to test the script using Python3 and just ensure it is fully operational?

**Comment by musically-ut** [comment]
Mostly that, yes.

  1. Fork the repository.
  2. Create a new branch on your repository with the name `feat-python-3` (for example, this can be any name you want.)
  3. Make some changes, test them, commit to that branch and make a Pull Request to this repository from that branch (Github will show helpful Green buttons to do that as soon as you push your branch to your fork).
  4. I'll make comments on your pull request.
  5. Make more changes to your branch and then push them (they will automatically be appended to your pull request).
  6. Repeat 4 -- 5 until we are happy with the changes.
  7. We'll merge in the changes.
  8. 🎉

Also, as I'll be traveling over the holidays, I may not be able to give feedback immediately; please allow for a few days for it.

Have fun!

**Comment by italo-batista** [comment]
there is no one assigned. can i try?

**Comment by musically-ut** [comment]
@italo-batista Sure!

**Comment by italo-batista** [comment]
Please, check my pull request! :)
